version: '3.7' 
services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile 
    image: app 
    container_name: app 
    command: gunicorn --bind 0.0.0.0:8000 "app:app"
    expose: 
      - 8000 
    depends_on: 
      - redis-server
  nginx: 
    build: ./nginx 
    image: nginx 
    container_name: nginx 
    ports: 
      - 8000:80 
    depends_on: 
      - app 
  redis-server: 
    image: redis:alpine
    container_name: redis-server
